# SSH Algorithm Security Scanner - Configuration File
# This configuration file contains ONLY the implemented options
# that are actually used by the sshscan.py script

# ====================================================================
# SCANNER CONFIGURATION
# ====================================================================
[scanner]
# Number of concurrent scanning threads (1-500)
# Higher values = faster scanning but more resource usage
# Recommended: 20-50 for most networks
threads = 30

# Connection timeout in seconds (1-120)
# How long to wait for SSH connections before giving up
# Recommended: 10s for reliable networks, 20-30s for slow networks
timeout = 15

# Enable SSH connection multiplexing for better performance (true/false)
# Reuses SSH connections for multiple algorithm tests (80-90% faster)
# Disable only if experiencing connection issues with specific SSH servers
use_multiplexing = true

# Number of retry attempts for failed connections (1-10)
# Exponential backoff is used between retries
retry_attempts = 3

# DNS cache TTL in seconds (60-3600)
# How long to cache DNS lookups to avoid redundant queries
# Recommended: 300s (5 min) for most cases, 600s+ for large batch scans
dns_cache_ttl = 600

# ====================================================================
# COMPLIANCE CONFIGURATION
# ====================================================================
[compliance]
# Compliance framework to check against
# Available frameworks:
#   - NIST: NIST Cybersecurity Framework (balanced)
#   - FIPS_140_2: FIPS 140-2 Level 1 (strict)
#   - BSI_TR_02102: German BSI TR-02102-4 (very strict)
#   - ANSSI: French ANSSI guidelines (highest security)
#   - PRIVACY_FOCUSED: Anti-surveillance framework (excludes NSA-suspicious algorithms)
framework = "NIST"

# ====================================================================
# EXAMPLE CONFIGURATIONS
# ====================================================================

# Example: High-security privacy-focused configuration
# [scanner]
# threads = 50
# timeout = 12
# use_multiplexing = true
# retry_attempts = 3
# dns_cache_ttl = 600
# 
# [compliance]
# framework = "PRIVACY_FOCUSED"

# Example: Fast scanning for large networks
# [scanner]
# threads = 100
# timeout = 5
# use_multiplexing = true
# retry_attempts = 2
# dns_cache_ttl = 1200
# 
# [compliance]
# framework = "NIST"

# Example: Conservative configuration for unreliable networks
# [scanner]
# threads = 10
# timeout = 30
# use_multiplexing = false
# retry_attempts = 5
# dns_cache_ttl = 300
# 
# [compliance]
# framework = "FIPS_140_2"
