# Privacy-Focused SSH Scanner Configuration
# Designed to detect and avoid NSA-suspicious algorithms

[scanner]
threads = 30
timeout = 12
use_multiplexing = true
retry_attempts = 3
dns_cache_ttl = 600

[compliance]
# Use privacy-focused framework that excludes NSA-suspicious algorithms
framework = "PRIVACY_FOCUSED"
minimum_score = 90
fail_on_non_compliance = true

[algorithms]
# Explicitly test for NSA-suspicious algorithms to warn about them
check_nsa_suspicious = [
    # NSA-suspicious key exchange algorithms
    "ecdh-sha2-nistp256",
    "ecdh-sha2-nistp384", 
    "ecdh-sha2-nistp521",
    
    # NSA-suspicious host key algorithms
    "ecdsa-sha2-nistp256",
    "ecdsa-sha2-nistp384",
    "ecdsa-sha2-nistp521"
]

# Trusted algorithms (independently developed, no NSA involvement)
trusted_algorithms = [
    # Key Exchange - safe curves
    "curve25519-sha256",
    "curve25519-sha256@libssh.org",
    
    # Host Keys - independently developed
    "ssh-ed25519",
    
    # Encryption - modern, independently developed
    "chacha20-poly1305@openssh.com",
    "aes256-gcm@openssh.com",
    "aes128-gcm@openssh.com",
    
    # MAC - Encrypt-then-MAC variants
    "hmac-sha2-256-etm@openssh.com",
    "hmac-sha2-512-etm@openssh.com"
]

[security]
# Enable NSA backdoor analysis by default
enable_nsa_analysis = true

# Prioritize algorithms without government involvement
prefer_independent_crypto = true

# Warn about algorithms with intelligence agency connections
warn_government_involvement = true

[output]
format = "table"
include_nsa_analysis = true
include_compliance = true
include_recommendations = true

[reporting]
# Generate privacy-focused security reports
privacy_focused_report = true
highlight_surveillance_risks = true
include_alternative_recommendations = true

# Report sections
sections = [
    "executive_summary",
    "nsa_backdoor_analysis", 
    "compliance_assessment",
    "algorithm_recommendations",
    "migration_timeline"
]

[alerts]
# Alert thresholds for NSA-suspicious algorithms
nsa_risk_threshold = 1  # Alert if any NSA-suspicious algorithms found
compliance_threshold = 90  # Minimum compliance score

# Alert messages
high_risk_message = "⚠️  CRITICAL: NSA backdoor-suspicious algorithms detected"
recommendation_message = "🔒 RECOMMENDED: Use Curve25519/Ed25519 for maximum privacy"

[migration]
# Migration recommendations for NSA-suspicious algorithms
priority_replacements = [
    # High priority: Replace NIST curves immediately
    { from = "ecdh-sha2-nistp256", to = "curve25519-sha256", priority = "CRITICAL" },
    { from = "ecdh-sha2-nistp384", to = "curve25519-sha256", priority = "CRITICAL" },
    { from = "ecdh-sha2-nistp521", to = "curve25519-sha256", priority = "CRITICAL" },
    { from = "ecdsa-sha2-nistp256", to = "ssh-ed25519", priority = "CRITICAL" },
    { from = "ecdsa-sha2-nistp384", to = "ssh-ed25519", priority = "CRITICAL" },
    { from = "ecdsa-sha2-nistp521", to = "ssh-ed25519", priority = "CRITICAL" },
    
    # Medium priority: Legacy algorithms
    { from = "ssh-rsa", to = "ssh-ed25519", priority = "HIGH" },
    { from = "diffie-hellman-group14-sha256", to = "curve25519-sha256", priority = "MEDIUM" }
]

# Estimated migration timeline
timeline_weeks = 4  # Recommended timeframe for full migration
